<a href="https://colab.research.google.com/github/andresvillamayor/Python-Geometria-Analitica/blob/master/numpy_inicio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Usando Numpy

In [1]:
import numpy as np

In [5]:
#  Constante y funciones matematicas 
print (np.e)  #  valor de E
print (np.pi) #  valor de pi
print (np.log(2))  #  valor de logaritmo de 2 

2.718281828459045
3.141592653589793
0.6931471805599453


Coleccion de elementos 

In [6]:
np.array([1,2,3])

array([1, 2, 3])

Saber el tipo de datos de la coleccion

In [8]:
a = np.array([3,4,5])
a.dtype  #  Valor de dato int

dtype('int64')

In [9]:
b = np.array([1.,2.0,3.1])
b.dtype  #  valor de dato float

dtype('float64')

Cambiar los valores del array 

In [12]:
a = np.array([1,2,3],dtype= float)  # se cambio un array de numero enteros a float 
print (a)
print (a.dtype)

[1. 2. 3.]
float64


In [13]:
b = np.array([1,2,3],dtype = complex) #  se cambia  un array de numero entros a complex
print (b)
print (b.dtype)

[1.+0.j 2.+0.j 3.+0.j]
complex128


Otra forma es usado astype

In [19]:
x = np.array([1,2,2.5])
print (x)

[1.  2.  2.5]


In [21]:
x.astype(int) #  pasa a valor integer 

array([1, 2, 2])